export const shops = [
  { label: "Mercadona", value: "Mercadona" },
  { label: "Carrefour", value: "Carrefour" },
  { label: "Dia", value: "Dia" },
  { label: "Digi", value: "Digi" },
  { label: "Lidl", value: "Lidl" },
  { label: "Auchan", value: "Auchan" },
  { label: "Eroski", value: "Eroski" },
  { label: "Shein", value: "Shein" },
  { label: "Ali Express", value: "Ali Express" },
  { label: "Zalando", value: "Zalando" },
  { label: "Asos", value: "Asos" },
  { label: "Hipercor", value: "Hipercor" },
  { label: "Aldi", value: "Aldi" },
  { label: "Bricomart", value: "Bricomart" },
  { label: "Bricodepot", value: "Bricodepot" },
  { label: "Decathlon", value: "Decathlon" },
  { label: "Media Markt", value: "Media Markt" },
  { label: "Fnac", value: "Fnac" },
  { label: "Amazon", value: "Amazon" },
  { label: "Kebab", value: "Kebab" },
  { label: "Bazar", value: "Bazar" },
  { label: "Consum", value: "Consum" },
  { label: "Hipercor", value: "Hipercor" },
  { label: "Bon Àrea", value: "Bon Àrea" },
  { label: "El Corte Inglés", value: "El Corte Inglés" },
  { label: "Zara", value: "Zara" },
  { label: "Pull & Bear", value: "Pull & Bear" },
  { label: "Bershka", value: "Bershka" },
  { label: "Stradivarius", value: "Stradivarius" },
  { label: "C&A", value: "C&A" },
  { label: "Bimba y Lola", value: "Bimba y Lola" },
  { label: "Massimo Dutti", value: "Massimo Dutti" },
  { label: "Mango", value: "Mango" },
  { label: "Bolera", value: "Bolera" },
  { label: "Cinesa", value: "Cinesa" },
  { label: "Primark", value: "Primark" },
  { label: "Boots", value: "Boots" },
  { label: "Argos", value: "Argos" },
  { label: "Game", value: "Game" },
  { label: "Ikea", value: "Ikea" },
  { label: "B&Q", value: "B&Q" },
  { label: "ICA", value: "ICA" },
  { label: "Coop", value: "Coop" },
  { label: "Apoteket", value: "Apoteket" },
  { label: "Lindex", value: "Lindex" },
  { label: "S-Market", value: "S-Market" },
  { label: "Prisma", value: "Prisma" },
  { label: "Sale", value: "Sale" },
  { label: "K-Market", value: "K-Market" },
  { label: "Hemköp", value: "Hemköp" },
  { label: "OAS", value: "OAS" },
  { label: "Normal", value: "Normal" },
  { label: "H&M", value: "H&M" },
  // restaurants
  { label: "McDonalds", value: "McDonalds" },
  { label: "Burger King", value: "Burger King" },
  { label: "Subway", value: "Subway" },
  { label: "Hesburger", value: "Hesburger" },
  { label: "KFC", value: "KFC" },
  { label: "Pizza Hut", value: "Pizza Hut" },
  { label: "Wok", value: "Wok" },
  { label: "COndis", value: "COndis" },
  { label: "Juanitas tapas", value: "Juanitas tapas" },
  { label: "Sushi", value: "Sushi" },
  { label: "Thai", value: "Thai" },
  { label: "Indian", value: "Indian" },
  { label: "Chinese", value: "Chinese" },
  { label: "Italian", value: "Italian" },
  { label: "Mexican", value: "Mexican" },
  { label: "Japanese", value: "Japanese" },
  { label: "Greek", value: "Greek" },
  { label: "Spanish", value: "Spanish" },
  { label: "French", value: "French" },
  { label: "German", value: "German" },

  // Bars
  { label: "Bar", value: "Bar" },
  { label: "Pub", value: "Pub" },
  { label: "Club", value: "Club" },

  // Cafes
  { label: "Starbucks", value: "Starbucks" },
  { label: "365", value: "365" },
  { label: "Granier", value: "Granier" },
  { label: "Bar Maresme", value: "Bar Maresme" },

  // Rent
  { label: "Rent", value: "Rent" },
  { label: "Mortgage", value: "Mortgage" },

  // Bills
  { label: "Electricity", value: "Electricity" },
  { label: "Water", value: "Water" },
  { label: "Internet", value: "Internet" },
  { label: "Phone", value: "Phone" },
  { label: "TV", value: "TV" },
  { label: "Insurance", value: "Insurance" },
  { label: "Gas", value: "Gas" },
  { label: "Heating", value: "Heating" },
  { label: "Garbage", value: "Garbage" },
  { label: "Tax", value: "Tax" },

  // Transport
  { label: "Gasoil", value: "Gasoil" },
  { label: "Diesel", value: "Diesel" },
  { label: "Parking", value: "Parking" },
  { label: "Toll", value: "Toll" },
  { label: "Taxi", value: "Taxi" },
  { label: "Bus", value: "Bus" },
  { label: "Train", value: "Train" },
  { label: "Plane", value: "Plane" },
  { label: "Car", value: "Car" },
  { label: "ATM", value: "ATM" },
  { label: "Bike", value: "Bike" },
  { label: "Boat", value: "Boat" },

  // Health
  { label: "Doctor", value: "Doctor" },
  { label: "Dentist", value: "Dentist" },
  { label: "Pharmacy", value: "Pharmacy" },
  { label: "Hospital", value: "Hospital" },
  { label: "Clinic", value: "Clinic" },
  { label: "Optician", value: "Optician" },

  // Entertainment
  { label: "Cinema", value: "Cinema" },
  { label: "Bowling", value: "Bowling" },
  { label: "Theatre", value: "Theatre" },
  { label: "Concert", value: "Concert" },
  { label: "Opera", value: "Opera" },
  { label: "Museum", value: "Museum" },
  { label: "Exhibition", value: "Exhibition" },
  { label: "Festival", value: "Festival" },
  { label: "Party", value: "Party" },
  { label: "Zoo", value: "Zoo" },
  { label: "Aquarium", value: "Aquarium" },
  { label: "Theme Park", value: "Theme Park" },
  { label: "Casino", value: "Casino" },
  { label: "Monument", value: "Monument" },
  { label: "Gym", value: "Gym" },
  { label: "Sports", value: "Sports" },
  { label: "Swimming", value: "Swimming" },
  { label: "Yoga", value: "Yoga" },
  { label: "Disco", value: "Disco" },
  { label: "Music", value: "Music" },
  { label: "Karaoke", value: "Karaoke" },
  { label: "Dance", value: "Dance" },
  { label: "Comedy", value: "Comedy" },
  { label: "Circus", value: "Circus" },

  // Other
  { label: "Bizzum", value: "Bizzum" },
  { label: "Other", value: "Other" },
];
