export const categories = [
  {
    label: "Food",
    options: [
      { label: "Fruit", value: "Fruit" },
      { label: "Vegetables", value: "Vegetables" },
      { label: "Meat", value: "Meat" },
      { label: "Fish", value: "Fish" },
      { label: "Dairy", value: "Dairy" },
      { label: "Eggs", value: "Eggs" },
      { label: "Bread", value: "Bread" },
      { label: "Pizza", value: "Pizza" },
      { label: "Grains", value: "Grains" },
      { label: "Snacks", value: "Snacks" },
      { label: "Sauces", value: "Sauces" },
      { label: "Legumes", value: "Legumes" },
      { label: "Nuts", value: "Nuts" },
      { label: "Sweets", value: "Sweets" },
      { label: "Drinks", value: "Drinks" },
    ],
  },
  {
    label: "Complete meals",
    options: [
      { label: "Breakfast", value: "Breakfast" },
      { label: "Lunch", value: "Lunch" },
      { label: "Snack", value: "Snack" },
      { label: "Dinner", value: "Dinner" },
    ],
  },
  {
    label: "Household",
    options: [
      { label: "Cleaning", value: "Cleaning" },
      { label: "Laundry", value: "Laundry" },
      { label: "Toiletries", value: "Toiletries" },
    ],
  },
  {
    label: "Transport",
    options: [
      { label: "Fuel", value: "Fuel" },
      { label: "Maintenance", value: "Maintenance" },
      { label: "Parking", value: "Parking" },
      { label: "Public Transport", value: "Public Transport" },
    ],
  },
  {
    label: "Entertainment",
    options: [
      { label: "Movies", value: "Movies" },
      { label: "Music", value: "Music" },
      { label: "Games", value: "Games" },
    ],
  },
  {
    label: "Clothes",
    options: [
      { label: "Clothes", value: "Clothes" },
      { label: "Shoes", value: "Shoes" },
      { label: "Accessories", value: "Accessories" },
    ],
  },
  {
    label: "Electronics",
    options: [
      { label: "Electronics", value: "Electronics" },
      { label: "Computers", value: "Computers" },
      { label: "Phones", value: "Phones" },
    ],
  },
  {
    label: "Hobbies",
    options: [
      { label: "Books", value: "Books" },
      { label: "Sports", value: "Sports" },
      { label: "Gaming", value: "Gaming" },
      { label: "Hobbies", value: "Hobbies" },
    ],
  },
  {
    label: "Pets",
    options: [
      { label: "Pet Toys", value: "Pet Toys" },
      { label: "Vet", value: "Vet" },
      { label: "Pet Accessories", value: "Pet Accessories" },
    ],
  },
  {
    label: "Travel",
    options: [
      { label: "Tickets", value: "Tickets" },
      { label: "Accommodation", value: "Accommodation" },
      { label: "Transport", value: "Transport" },
    ],
  },
  {
    label: "Hygiene",
    options: [
      { label: "Shower", value: "Shower" },
      { label: "Haircut", value: "Haircut" },
      { label: "Hair products", value: "Hair products" },
      { label: "Makeup", value: "Makeup" },
      { label: "Nails", value: "Nails" },
      { label: "Cosmetics", value: "Cosmetics" },
      { label: "Toothpaste", value: "Toothpaste" },
      { label: "Tampax", value: "Tampax" },
      { label: "Deodorant", value: "Deodorant" },
      { label: "Shaving", value: "Shaving" },
      { label: "Feminine hygiene", value: "Feminine hygiene" },
    ],
  },
  {
    label: "Health",
    options: [
      { label: "Medicine", value: "Medicine" },
      { label: "Doctor", value: "Doctor" },
      { label: "Dentist", value: "Dentist" },
      { label: "Gym", value: "Gym" },
    ],
  },
  {
    label: "Other",
    options: [
      { label: "Gift", value: "Gift" },
      { label: "Plant", value: "Plant" },

      { label: "Other", value: "Other" },
    ],
  },
];

export const shops = [
  { label: "Mercadona", value: "Mercadona" },
  { label: "Carrefour", value: "Carrefour" },
  { label: "Dia", value: "Dia" },
  { label: "Lidl", value: "Lidl" },
  { label: "Alcampo", value: "Alcampo" },
  { label: "Eroski", value: "Eroski" },
  { label: "Hipercor", value: "Hipercor" },
  { label: "Aldi", value: "Aldi" },
  { label: "Bricomart", value: "Bricomart" },
  { label: "Bricodepot", value: "Bricodepot" },
  { label: "Decathlon", value: "Decathlon" },
  { label: "Media Markt", value: "Media Markt" },
  { label: "Fnac", value: "Fnac" },
  { label: "El Corte Inglés", value: "El Corte Inglés" },
  { label: "Zara", value: "Zara" },
  { label: "Pull & Bear", value: "Pull & Bear" },
  { label: "Bershka", value: "Bershka" },
  { label: "Stradivarius", value: "Stradivarius" },
  { label: "C&A", value: "C&A" },
  { label: "Bimba y Lola", value: "Bimba y Lola" },
  { label: "Massimo Dutti", value: "Massimo Dutti" },
  { label: "Mango", value: "Mango" },
  { label: "Bolera", value: "Bolera" },
  { label: "Cinesa", value: "Cinesa" },
  { label: "Primark", value: "Primark" },
  { label: "Boots", value: "Boots" },
  { label: "Argos", value: "Argos" },
  { label: "Game", value: "Game" },
  { label: "Ikea", value: "Ikea" },
  { label: "B&Q", value: "B&Q" },
  { label: "ICA", value: "ICA" },
  { label: "Coop", value: "Coop" },
  { label: "Apoteket", value: "Apoteket" },
  { label: "Lindex", value: "Lindex" },
  { label: "S-Market", value: "S-Market" },
  { label: "Prisma", value: "Prisma" },
  { label: "Sale", value: "Sale" },
  { label: "K-Market", value: "K-Market" },
  { label: "Hemköp", value: "Hemköp" },
  { label: "Normal", value: "Normal" },
  { label: "H&M", value: "H&M" },
  // restaurants
  { label: "McDonalds", value: "McDonalds" },
  { label: "Burger King", value: "Burger King" },
  { label: "Subway", value: "Subway" },
  { label: "Hesburger", value: "Hesburger" },
  { label: "KFC", value: "KFC" },
  { label: "Pizza Hut", value: "Pizza Hut" },
  { label: "Wok", value: "Wok" },
  { label: "Sushi", value: "Sushi" },
  { label: "Thai", value: "Thai" },
  { label: "Indian", value: "Indian" },
  { label: "Chinese", value: "Chinese" },
  { label: "Italian", value: "Italian" },
  { label: "Mexican", value: "Mexican" },
  { label: "Japanese", value: "Japanese" },
  { label: "Greek", value: "Greek" },
  { label: "Spanish", value: "Spanish" },
  { label: "French", value: "French" },
  { label: "German", value: "German" },

  // bars
  { label: "Bar", value: "Bar" },
  { label: "Pub", value: "Pub" },
  { label: "Club", value: "Club" },

  // cafes
  { label: "Starbucks", value: "Starbucks" },
  { label: "365", value: "365" },
  { label: "Granier", value: "Granier" },

  // Rent
  { label: "Rent", value: "Rent" },

  // Bills
  { label: "Electricity", value: "Electricity" },
  { label: "Water", value: "Water" },
  { label: "Internet", value: "Internet" },
  { label: "Phone", value: "Phone" },
  { label: "TV", value: "TV" },
  { label: "Insurance", value: "Insurance" },
  { label: "Gas", value: "Gas" },
  { label: "Heating", value: "Heating" },
  { label: "Garbage", value: "Garbage" },
  { label: "Tax", value: "Tax" },

  // Transport
  { label: "Gasoil", value: "Gasoil" },
  { label: "Diesel", value: "Diesel" },
  { label: "Parking", value: "Parking" },
  { label: "Toll", value: "Toll" },
  { label: "Taxi", value: "Taxi" },
  { label: "Bus", value: "Bus" },
  { label: "Train", value: "Train" },
  { label: "Plane", value: "Plane" },
  { label: "Car", value: "Car" },
  { label: "ATM", value: "ATM" },
  { label: "Bike", value: "Bike" },
  { label: "Boat", value: "Boat" },

  // Health
  { label: "Doctor", value: "Doctor" },
  { label: "Dentist", value: "Dentist" },
  { label: "Pharmacy", value: "Pharmacy" },
  { label: "Hospital", value: "Hospital" },
  { label: "Clinic", value: "Clinic" },
  { label: "Optician", value: "Optician" },

  // Entertainment
  { label: "Cinema", value: "Cinema" },
  { label: "Bowling", value: "Bowling" },
  { label: "Theatre", value: "Theatre" },
  { label: "Concert", value: "Concert" },
  { label: "Opera", value: "Opera" },
  { label: "Museum", value: "Museum" },
  { label: "Exhibition", value: "Exhibition" },
  { label: "Festival", value: "Festival" },
  { label: "Party", value: "Party" },
  { label: "Zoo", value: "Zoo" },
  { label: "Aquarium", value: "Aquarium" },
  { label: "Theme Park", value: "Theme Park" },
  { label: "Casino", value: "Casino" },
  { label: "Monument", value: "Monument" },

  // Other
  { label: "Bizzum", value: "Bizzum" },
  { label: "Other", value: "Other" },
];
