export interface ILabelValue {
  label: string;
  value: string;
}

export const initialValueShops = [
  {
    label: "Supermercados",
    options: [
      { label: "Ikea", value: "Ikea" },
      { label: "Coop", value: "Coop" },
      { label: "Maxi ICA", value: "ICA" },
      { label: "Lidl", value: "Lidl" },
      { label: "Alcampo", value: "Alcampo" },
      { label: "Mercadona", value: "Mercadona" },
      { label: "Carrefour", value: "Carrefour" },
      { label: "Dia", value: "Dia" },
      { label: "Aldi", value: "Aldi" },
      { label: "Eroski", value: "Eroski" },
      { label: "Leroy Merlin", value: "Leroy Merlin" },
      { label: "Bricomart", value: "Bricomart" },
      { label: "Bricodepot", value: "Bricodepot" },
      { label: "Decathlon", value: "Decathlon" },
      { label: "Media Markt", value: "Media Markt" },
      { label: "El Corte Inglés", value: "El Corte Inglés" },
    ],
  },
  {
    label: "Ropa",
    options: [
      { label: "Zara", value: "Zara" },
      { label: "Pull & Bear", value: "Pull & Bear" },
      { label: "Bershka", value: "Bershka" },
      { label: "Stradivarius", value: "Stradivarius" },
      { label: "H&M", value: "H&M" },
      { label: "Bimba y Lola", value: "Bimba y Lola" },
      { label: "Massimo Dutti", value: "Massimo Dutti" },
      { label: "Oysho", value: "Oysho" },
    ],
  },
  {
    label: "Cafeterías",
    options: [
      { label: "Starbucks", value: "Starbucks" },
      { label: "365", value: "365" },
      { label: "Cafetería UAB", value: "Cafetería UAB" },
    ],
  },
  {
    label: "Restaurantes",
    options: [
      { label: "McDonalds", value: "McDonalds" },
      { label: "Burger King", value: "Burger King" },
      { label: "KFC", value: "KFC" },
      { label: "Subway", value: "Subway" },
      { label: "Pizza Hut", value: "Pizza Hut" },
      { label: "Domino's Pizza", value: "Domino's Pizza" },
      { label: "La Tagliatella", value: "La Tagliatella" },
    ],
  },
  {
    label: "Transporte",
    options: [
      { label: "TMB", value: "TMB" },
      { label: "Avión", value: "Avión" },
      { label: "Tren", value: "Tren" },
      { label: "Metro", value: "Metro" },
      { label: "Autobús", value: "Autobús" },
      { label: "Taxi", value: "Taxi" },
      { label: "Uber", value: "Uber" },
      { label: "Bici", value: "Bici" },
      { label: "Coche", value: "Coche" },
      { label: "Moto", value: "Moto" },
    ],
  },
  {
    label: "Otros",
    options: [
      { label: "Hotel", value: "Hotel" },
      { label: "Alquier", value: "Alquier" },
      { label: "Camping", value: "Camping" },
      { label: "Alquiler de coches", value: "Alquiler de coches" },
      { label: "Gasolinera", value: "Gasolinera" },
      { label: "Cajero", value: "Cajero" },
      { label: "Cine", value: "Cine" },
      { label: "Banco", value: "Banco" },
      { label: "Farmacia", value: "Farmacia" },
      { label: "Hospital", value: "Hospital" },
      { label: "Carnicería", value: "Carnicería" },
      { label: "Pescadería", value: "Pescadería" },
      { label: "Panadería", value: "Panadería" },
      { label: "Ferretería", value: "Ferretería" },
      { label: "Floristería", value: "Floristería" },
      { label: "Peluquería", value: "Peluquería" },
      { label: "Estanco", value: "Estanco" },
      { label: "Librería", value: "Librería" },
      { label: "Óptica", value: "Óptica" },
      { label: "Zoo", value: "Zoo" },
      { label: "Museo", value: "Museo" },
      { label: "Teatro", value: "Teatro" },
      { label: "Circo", value: "Circo" },
      { label: "Circuito", value: "Circuito" },
      { label: "Parque de atracciones", value: "Parque de atracciones" },
      { label: "Parque acuático", value: "Parque acuático" },
    ],
  },
];
